# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77a7a6851a999370e09aa8880aab12dc54b2744ada8b2e4ac26bff3aa6701f726c36a7a167fc27a19c91372041d8d4003f961a7a8bcbe291c81c24f3c7da3016

test:
  secret_key_base: f62b1452074972e5ed6a3d1c54c48253e42eae1eab678f4257d868ac3d552b52d7a45db72ddff3c9a996d3b8d8dc87621f80c7d259bbc1fb5fbd93dcf07bb97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
